# Setup and configure mongodb for reddit app
- name: "Reddit App: Install MongoDB 4.0"
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Add MongoDB repo key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.0.asc
        state: present

    - name: Add MongoDB repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
        state: present
        filename: mongodb-org-4.0.list        

    - name: Install MongoDB package
      apt:
        update_cache: yes
        pkg: mongodb-org
        state: present
      notify: start mongod

    - name: Enable MongoDB service
      systemd: name=mongod enabled=yes
  handlers:
    - name: start mongod
      systemd: name=mongod state=started
